apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rcorderoayigroup/my-app.git
    targetRevision: HEAD
    path: overlays/test
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true